# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            34_Space
tagline:          'A Jekyll theme'
description:      '紀錄程式心得以及存放基礎程式碼'
url:              ''
baseurl:          'https://b013040034.github.io/ohmyblog/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins:          [jekyll-paginate]
