# Dependencies
markdown:         kramdown
highlighter:      rouge
# Permalinks
# permalink:        pretty

# Setup
title:            34_Space
tagline:          ''
description:      '紀錄程式心得以及存放基礎程式碼'
url:              'http://127.0.0.1:4000'
baseurl:          "/"
#url:              '/ohmyblog'
#baseurl:          "https://b013040034.github.io/ohmyblog/"



author:
  name:           'Aslan Yan'
  url:            https://www.facebook.com/profile.php?id=100000032170714&ref=bookmarks

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/B013040034/ohmyblog
plugins:          [jekyll-paginate]
